### ISSUE TITLE
Latest staging version fails to show pages, looking for ads.txt or app_ads.txt

### ISSUE THREAD

**Issue by tjoneslo** [PlanoramaEvents/planorama#772]
I pulled the latest staging version and restarted the docker compose. Now none of the applications will show up in the browser. 

The web log has the following error message: 

```
$ tail /var/log/planorama/web/planorama.log
# Logfile created on 2022-10-29 08:43:37 +0000 by logger.rb/v1.4.2F, [2022-10-29T08:43:37.849711 #32] 
FATAL -- :   ActionController::RoutingError (No route matches [GET] "/ads.txt"):
 F, [2022-10-29T08:43:38.054530 #32] FATAL -- :   ActionController::RoutingError (No route matches [GET] "/app-ads.txt"): 
```

**Comment by balen** [comment]
There are no such files ads.txt etc in the code or docker image. If you are seeing this in the log it is probably because a browser or bot is requesting this "file", a routing error should effectively result in a 401 (not found) response to the client.

**Comment by balen** [comment]
Closing because this was a start timing error
